openapi: 3.0.0
info:
  title: Trade Finance Doc Processing API
  description: API to accept at least one PDF file (mandatory) and optionally a second file, then process them with detailed verification checks.
  version: 1.0.0
servers:
  - url: https://tradefdocvalidation.dev.edocsafeai.corporateidplatform.com
  - url: http://localhost:4000

paths:
  /process-pdfs:
    post:
      summary: Process one or two PDF files
      description: Accepts at least one PDF file (mandatory) and optionally a second file. Performs a series of verification checks and returns a JSON report detailing the results and a risk rating (Red/Amber/Green).
      tags:
        - PDF Processing
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  minItems: 1
                  maxItems: 2
                  description: At least 1 PDF file (mandatory) and optionally 1 additional PDF file.
      responses:
        '200':
          description: Successfully processed PDF files with detailed verification results.
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice_checks:
                    type: object
                    properties:
                      basic_information_verification:
                        type: object
                        properties:
                          invoice_number: { type: string }
                          date_of_issue: { type: string }
                          seller_name: { type: string }
                          seller_address: { type: string }
                          buyer_name: { type: string }
                          buyer_address: { type: string }
                      goods_description:
                        type: object
                        properties:
                          goods_description: { type: string }
                          quantity: { type: string }
                          total_value: { type: string }
                          currency: { type: string }
                      payment_terms:
                        type: object
                        properties:
                          payment_terms: { type: string }
                          due_date: { type: string }
                  bill_of_lading_checks:
                    type: object
                    properties:
                      basic_information_verification:
                        type: object
                        properties:
                          B/L_number: { type: string }
                          date_of_issue: { type: string }
                          exporter_details: { type: string }
                          importer_details: { type: string }
                      goods_description:
                        type: object
                        properties:
                          goods_description: { type: string }
                          quantity: { type: string }
                          weight: { type: string }
                      shipment_terms:
                        type: object
                        properties:
                          port_of_loading: { type: string }
                          port_of_discharge: { type: string }
                          incoterms: { type: string }
                          carrier_signature: { type: string }
                      freight_information:
                        type: object
                        properties:
                          freight_payment_status: { type: string }
                          freight_charges: { type: string }
                      delivery_terms:
                        type: object
                        properties:
                          expected_delivery_date: { type: string }
                          carrier_liabilities: { type: string }
                  cross_document_consistency_checks:
                    type: object
                    properties:
                      goods_description_match: { type: string }
                      quantity_match: { type: string }
                      weight_match: { type: string }
                      incoterms_match: { type: string }
                      payment_and_shipping_terms_match: { type: string }
                  summary:
                    type: object
                    properties:
                      overall_consistency: { type: string }
                      key_discrepancies: { type: string }
                      notes: { type: string }
                      risk_rating: { type: string }
        '400':
          description: Invalid request, such as missing the required file or exceeding the allowed number of files.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Please upload at least one PDF file."
        '500':
          description: Server error while processing the request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "An error occurred while processing the request."
                  details:
                    type: string
                    example: "Error details"